---
title: "Week 5 In-class Assignment "
format: pdf
editor: visual
---

Load in libraries:

```{r}
library(tidyverse)
library(here)
library(texreg)
library(multgee)
library(table1)
library(here)
```

Load in data:

```{r}
data <- read.csv(here("original","analytical", "finaldata.csv"),header=TRUE)
```

Factor and filter data:

```{r}

data_2000 <- filter(data, year == 2000)


data$conflict <- factor(data_2000$conflict,levels=c(0,1),labels=c("No Conflict","Conflict"))

data$gdp1000 <- cut(data_2000$gdp1000, 
                    breaks = c(-Inf, 1.2383, 4.0719, 13.1531, Inf),
                    labels = c("Very Low GDP", "Low GDP", "Medium GDP", "High GDP"),
                    right = FALSE)

data$OECD <- factor(data_2000$OECD, levels =c(0,1), labels=c("Non-member","Member"))


```

Create labels, caption, and footnote:

```{r}
label(data_2000$gdp1000) <- "GDP"
label(data_2000$OECD) <- "OECD"
label(data_2000$popdens) <- "Population Density"
label(data_2000$urban) <- "Urban Residence"
label(data_2000$conflict) <- c("No Conflict","Conflict")

caption <- "Armed Conflict Description of Data in 2000"

footnote <- "No conflict: <25 battle-related deaths per year<br>Conflict: >=25 battle-related deaths per year"

```

Create table:

```{r}
table1( ~ gdp1000 + OECD + popdens + urban | conflict, data = data_2000, overall=(c(Left="Total")), caption = caption, footnote = footnote)

```
